-- Kyno Database Schema for Supabase
-- Run this in Supabase SQL Editor: https://app.supabase.com/project/_/sql

-- 1. Creators (designers who sell on the platform)
CREATE TABLE IF NOT EXISTS creators (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  bio TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  password_hash TEXT NOT NULL,
  commission INTEGER DEFAULT 20,
  total_sales INTEGER DEFAULT 0,
  total_earnings REAL DEFAULT 0,
  status TEXT DEFAULT 'active',
  permissions JSONB DEFAULT '{"canUpload":true,"canEdit":true,"canDelete":false,"canViewAnalytics":true}',
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_creators_email ON creators(email);
CREATE INDEX IF NOT EXISTS idx_creators_username ON creators(username);

-- 2. Users (regular customers)
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- 3. Products
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  original_price REAL,
  creator TEXT NOT NULL DEFAULT 'Kyno',
  creator_id TEXT,
  description TEXT DEFAULT '',
  features JSONB DEFAULT '[]',
  includes JSONB DEFAULT '[]',
  preview_images JSONB DEFAULT '[]',
  download_file JSONB,
  created_at TEXT DEFAULT '',
  updated_at TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_creator_id ON products(creator_id);

-- 4. Orders
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER DEFAULT 0,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  price REAL NOT NULL,
  customer_email TEXT DEFAULT '',
  customer_name TEXT DEFAULT '',
  download_token TEXT NOT NULL UNIQUE,
  download_claimed BOOLEAN DEFAULT false,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_orders_download_token ON orders(download_token);

-- 5. Affiliates
CREATE TABLE IF NOT EXISTS affiliates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  commission INTEGER DEFAULT 20,
  total_earnings REAL DEFAULT 0,
  paid_earnings REAL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_affiliates_code ON affiliates(code);

-- 6. Affiliate clicks
CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  converted BOOLEAN DEFAULT false,
  order_id INTEGER,
  commission REAL
);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_code ON affiliate_clicks(code);

-- Enable Row Level Security (RLS) — default deny
ALTER TABLE creators ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE affiliate_clicks ENABLE ROW LEVEL SECURITY;

-- Create policies using auth.uid() for the admin/service role
-- In production, use the service_role key for server-side operations
CREATE POLICY "Authenticated can read all products" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated can insert products" ON products FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated can update products" ON products FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated can delete products" ON products FOR DELETE TO authenticated USING (true);
